batch_type: folded
batch_size: 64
accum_grad: 1    # gradient accumulation steps
max_epoch: 150
patience: none
init: xavier_uniform
best_model_criterion:  # criterion to save best models
  -   - valid
      - acc
      - max
keep_nbest_models: 10  # save nbest models and average these checkpoints
# use_amp: true    # whether to use automatic mixed precision
num_att_plot: 0  # do not save attention plots to save time in the demo
num_workers: 1   # number of workers in dataloader
pad_length_to_pow2: true
pad_batch_to_pow2: true

encoder: transformer
encoder_conf:
  output_size: 256
  attention_heads: 4
  linear_units: 1024
  num_blocks: 12
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  attention_dropout_rate: 0.1
  input_layer: conv2d
  normalize_before: true

decoder: transformer
decoder_conf:
  attention_heads: 4
  linear_units: 1024
  num_blocks: 3
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1

model_conf:
  ctc_weight: 0.3  # joint CTC/attention training
  lsm_weight: 0.1  # label smoothing weight
  length_normalized_loss: false

optim: adam

scheduler: warmuplr
scheduler_conf:
  peak_lr: 0.001
  warmup_steps: 800
